// <auto-generated />
using ApiBrawlstars.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiBrawlstars.Migrations
{
    [DbContext(typeof(DbBsContext))]
    [Migration("20240913123233_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiBrawlstars.Models.Brawlstar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lane")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raridade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brawlstars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2018,
                            Foto = "https://liquipedia.net/commons/images/f/f6/Brawl_Shelly.png",
                            Lane = "Lateral",
                            Nome = "Shelly",
                            Raridade = "Inicial",
                            Regiao = "Velho Oeste",
                            Status = "Ativo",
                            Tipo = "Destruidor"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2018,
                            Foto = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXTwLLQ1N2m6Li9bMtYmChaymQx1qZUtu2-A&s",
                            Lane = "Lateral",
                            Nome = "Nita",
                            Raridade = "Raro",
                            Regiao = "Tribo Shaman",
                            Status = "Ativo",
                            Tipo = "Destruidor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
